blank_issues_enabled: false
contact_links:
  - name: Silent Hill: United Discord
    url: https://discord.gg/dXqEzN54s
    about: Follow development, release news, multiplayer testing, and Resident Evil: United updates.
